config/routes.rb
Rails.application.routes.draw do

  resources :posts
  #get 'users/index'
  #get 'user/index'
  get 'friendships/index' => 'friendships#index'
  get "/users/blocked_users" => "users#blocked_users"
  get 'friends/destroy'
  resources :friend_requests
  #root to: 'pages#home'
  resources :users
  devise_for :users, skip: [:registrations], :path_prefix => 'd'
  resources :users, :only =>[:show]
  devise_scope :user do
    authenticated :user do
      #get 'users/edit' => 'users/users_edit_path', :as => 'edit_user_path'
      root 'users#index', as: :authenticated_root

    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  get "/posts/edit" => "posts_path"
  match '/users/:id',     to: 'users#show',       via: 'get'
  ##get 'users:id' => 'users#show'
  match '/users',   to: 'users#index',   via: 'get'
  post "/friendships/accept" => "friendships/accept"
  post "/friendships/remove" => "friendships/remove"
  post "/friendships/block" => "friendships/block"
  post "/friendships/unblock" => "friendships/unblock"
  post "/friendships/create" => "friendhsips/create"
  delete "/friendships/reject" => "friendships/reject"
  get "/friendships/requested_friends" => "friendships/requested_friends"
  get "/friendships/friends_request" => "friendships/friends_requests"
  get "/friendships/reject" => "friendships/reject"
  get "/friendships/create" => "friendhsips/create"
  resources :friendships, only: [:index, :create]

  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_friendship

  serialize :blocked_users, Array
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  def friends?
    self.friends
  end

  def friend_requests?
    self.requested_friends.any?
  end

  def requested_friends?
    self.pending_friends.any?
  end

  def blocked_friends?
    self.blocked_friends.any?
  end

  def blocked_user_email(user_id)
    User.find_by(id: user_id).email
  end

  def blocked_user_id(user_id)
    User.find_by(id: user_id)
  end

  def not_friends
    users_not_be_a_friends = []
    User.all.each do |user|
      if( (self.friends_with?(user) == false) &&
          (self != user && self.friends.include?(user) == false) &&
          (self.pending_friends.include?(user) == false) &&
          (self.requested_friends.include?(user) == false) &&
          (self.blocked_friendships.include?(user) == false) )
        users_not_be_a_friends.push user
      end
    end
    return users_not_be_a_friends
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
     @user = current_user
  end

  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update(user_params)
        format.js
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
        @user.save!
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def blocked_users
    @user = current_user
    @blocked = @user.blocked_users
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :surname, :date_of_birth, :description, :password, :password_confirmation)
  end

  def get_user(user_id)
    @user = current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/users/_create.html.erb
<%= link_to user.email, user_path(user), class: 'add_friend' %>
<%= form_tag ({controller: 'friendships', action: 'create', method: 'post', id: user.id, remote: true}) do %>
  <input class="ui basic button" type=submit value='Dodaj do znajomych'>
<% end %>

app/views/users/_inline_form.html.erb
<%= form_for @user, controller: 'users', action: 'update', remote: true do |form| %>

  <div class="field">

    <%= form.text_area :name %>
    <%= form.text_area :surname %>
    <%= form.text_area :date_of_birth %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>

  </div>

<% end %>

app/views/users/_user.html.erb
<strong>Imię:</strong>
<%= @user.name %>
<br>
<strong>Nazwisko</strong>
<%= @user.surname%>
<br>
<strong>Email:</strong>
<%= @user.email %>
<strong>Data urodzenia:</strong>
<%= @user.date_of_birth %>
<br>
<strong>Opis</strong>
<%= @user.description %>
<br>
<% if @user == current_user %>
  <%= link_to "Edit user", edit_user_path(@user), remote: true %>
<% end %>

app/views/users/blocked_users.html.erb
<b> Zablokowani: <b>
  <br>
<% if @user.blocked_users? %>
<br>

  <% @blocked.each do |user_id| %>
    <li> <%= @user.blocked_user_email(user_id) %> <li>
    <%= form_tag ({controller: 'friendships', action: 'unblock', method: 'post', id: @user.blocked_user_id(user_id) }) do %>
      <input class="ui basic button" type=submit value='Odblokuj'>
    <% end %>
  <% end %>

<% end %>
<br>
<%= link_to 'Back', users_path %>

app/views/users/edit.js.erb
document.getElementById('<%= dom_id(@user) %>').insertAdjacentHTML('afterend', "<%= j render 'inline_form', user: @user %>")
document.getElementById('<%= dom_id(@user) %>').style.display = 'none'

app/views/users/index.html.erb
<% current_user.not_friends.sample(5).each do |user| %>
  <table id="add_to_friend">
    <tr>
      <td>  <%= link_to user.email, user_path(user)%> </td>
      <td> <%= link_to "Dodaj do znajomych", {controller: 'friendships', action: 'create', method: :post, id: user.id, remote: true}, class: "create" %> </td>
    <tr>
  </table>
<% end %>

app/views/users/show.html.erb
<h1>Mój profil</h1>
<p>Find me in app/views/user/index.html.erb</p>

<div id="profile">
<div class="container">

  <%= link_to 'Twoi znajomi', friendships_path %>
  <%= link_to 'Wysłane zaproszenia', friendships_requested_friends_path %>
  <%= link_to 'Zablokowani użytkownicy', users_blocked_users_path %>

  <%= content_tag :div, class: 'divTableRow', id: dom_id(@user) do %>
      <%= render @user %>
    </p>
  <% end %>
</div>
</div>

app/views/users/update.js.erb
document.getElementById('<%= dom_id(@user, 'inline_form') %>' ).remove()
document.getElementById('<%= dom_id(@user) %>' ).innerHTML = "<%= j render @user %>"
document.getElementById('<%= dom_id(@user) %>' ).style.display = "table-row"