config/routes.rb
Rails.application.routes.draw do

  resources :posts
  #get 'users/index'
  #get 'user/index'
  get 'friendships/index' => 'friendships#index'
  get "/users/blocked_users" => "users#blocked_users"
  get 'friends/destroy'
  resources :friend_requests
  #root to: 'pages#home'
  resources :users
  devise_for :users, skip: [:registrations], :path_prefix => 'd'
  resources :users, :only =>[:show]
  devise_scope :user do
    authenticated :user do
      #get 'users/edit' => 'users/users_edit_path', :as => 'edit_user_path'
      root 'users#index', as: :authenticated_root

    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  get "/posts/edit" => "posts_path"
  match '/users/:id',     to: 'users#show',       via: 'get'
  ##get 'users:id' => 'users#show'
  match '/users',   to: 'users#index',   via: 'get'
  post "/friendships/accept" => "friendships/accept"
  post "/friendships/remove" => "friendships/remove"
  post "/friendships/block" => "friendships/block"
  post "/friendships/unblock" => "friendships/unblock"
  post "/friendships/create" => "friendhsips/create"
  delete "/friendships/reject" => "friendships/reject"
  get "/friendships/requested_friends" => "friendships/requested_friends"
  get "/friendships/friends_request" => "friendships/friends_requests"
  get "/friendships/reject" => "friendships/reject"
  get "/friendships/create" => "friendhsips/create"
  resources :friendships, only: [:index, :create]

  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    respond_to do |format|
      if @post.save
        format.js
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.js
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post =  Post.find_by(id: params[:id]).destroy
    respond_to do |format|
      format.js
      format.html { redirect_to root_path, notice: "Post został usunięty pomyślnie"}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:body)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with model: post, id: dom_id(post, 'form') do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_inline_form.html.erb
<%= form_with model: post, id: dom_id(post, 'inline_form') do |form| %>

  <div class="field">

    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>

  </div>
    <%= link_to "Cancel",posts_path, remote: true %>
<% end %>

app/views/posts/_post.html.erb
<tr>
  <td><%= post.body%></td> <td><%= post.user.email %></td>
  <td><%= link_to 'Show', post %></td>
  <td><%= link_to 'Edit', edit_post_path(post), remote: true, class: "update" %></td>
  <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Czy jesteś pewien?', remote: true}, class: "delete" %></td>
</tr>

app/views/posts/create.js.erb
$('#new-post form').remove();
//document.getElementById('<%= dom_id(@post, 'inline_form') %>' ).remove()
//document.getElementById('<%= dom_id(@post) %>' ).innerHTML = "<%= j render @post %>"
$('#new-post a').show();
//$('table#posts tbody').append("<%= j render @post %>")

app/views/posts/destroy.js.erb
$('.delete').bind('ajax:success', function(){
  $(this).closest('tr').fadeOut();
});

app/views/posts/edit.js.erb
document.getElementById('<%= dom_id(@post) %>').insertAdjacentHTML('afterend', "<%= j render 'inline_form', post: @post %>")
document.getElementById('<%= dom_id(@post) %>').style.display = 'none'

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>
<tbody>
  <% @posts.each do |post| %>
    <%= content_tag :div, id: dom_id(post) do %>
      <td><%= post.body %></td>
      <td><%= link_to 'Edit', edit_post_path(post), remote: true %> </td>
      <td><%= link_to 'Show', post %></td>
    <% end %>
<% end %>

<%= link_to 'Back', posts_path %>
</tbody>


<div id="new-post">
  <%= link_to 'New Post', new_post_path, remote: true %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render '_inline_form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/new.js.erb
$('#new-post a').hide().parent().append("<%= j render 'inline_form', post: @post%>")

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

app/views/posts/update.js.erb
document.getElementById('<%= dom_id(@post, 'inline_form') %>' ).remove()
document.getElementById('<%= dom_id(@post) %>' ).innerHTML = "<%= j render @post %>"
document.getElementById('<%= dom_id(@post) %>' ).style.display = "table-row"